spring:
  banner:
    location: classpath:/banner/banner.txt
    charset: utf-8

  application:
    name: startcraft

  config:
    import:
      - classpath:starcraft/starcraft-protoss.yml


message:
  hello: Hello, World!